[env:tab5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
upload_speed = 1500000
monitor_speed = 115200
build_type = debug
framework = arduino
board = esp32-p4-evboard
board_build.mcu = esp32p4
board_build.flash_mode = qio
board_build.partitions = partitions.csv
build_flags =
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=5
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DMBEDTLS_SSL_OUT_CONTENT_LEN=4096
  -DMBEDTLS_SSL_IN_CONTENT_LEN=4096
  -DCONFIG_MBEDTLS_DYNAMIC_FREE_PEER_CERT=1
  -DCONFIG_MBEDTLS_DYNAMIC_FREE_CONFIG_DATA=1
  -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
lib_deps =
  https://github.com/M5Stack/M5Unified.git
  https://github.com/M5Stack/M5GFX.git
  bblanchon/ArduinoJson@^7.0.0
  ricmoo/QRCode@^0.0.1